[project]
name = "open-vp-cal"
version = "1.3.0"
description = "The main package base for openvpcal without spg"
requires-python = "==3.11.*"
dependencies = [
    "colour-checker-detection>=0.2.1",
    "colour-science>=0.4.6",
    "matplotlib>=3.10.1",
    "opencolorio>=2.4.1",
    "openimageio==3.0.4.0",
    "packaging>=24.2",
    "pyqtgraph>=0.13.7",
    "pyside6>=6.8.2.1",
    "deepdiff"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
open_vp_cal = [
    "resources/*.png",
    "resources/*.exr",
    "resources/*.ttf",
    "resources/*.json",
    "resources/*.ico",
    "resources/*.layout"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
