[project]
name = "open-vp-cal-spg-icvfxpatterns"
version = "1.3.0"
description = "The spg part"
requires-python = "==3.11.*"
dependencies = [
    "opencolorio>=2.4.1",
    "openimageio==3.0.4.0",
    "packaging>=24.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
