name: Python CI/CD Workflow

on:
  push:
    branches:
      - feature/ci
  pull_request:
    branches:
      - feature/ci

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (no LFS)
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Build Python environment
        run: uv build

      - name: Run tests
        run: uv run pytest ./tests