name: Python CI/CD Workflow

on:
  push:
    branches:
      - feature/ci
  pull_request:
    branches:
      - feature/ci

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      # Restore the .git directory from the cache
      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ hashFiles('.git/HEAD') }}
          restore-keys:
            - ${{ runner.os }}-git-

      # Check out the repository with LFS support
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS support

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'