name: Python CI/CD Workflow

on:
  push:
    branches:
      - feature/ci
  pull_request:
    branches:
      - feature/ci

jobs:
  build:
    runs-on: macos-latest
    env:
      CI: true
    steps:
      - name: Checkout repository (no LFS)
        uses: actions/checkout@v3
        with:
          lfs: false

      # 2. Install Git LFS and disable automatic smudge (download)
      - name: Install Git LFS & disable auto-smudge
        run: |
          brew install git-lfs
          git lfs install --skip-smudge

      # 3. Fetch only the LFS files you need
      - name: Fetch specific LFS folder
        run: |
          git lfs fetch \
            --include="tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_balanced/**,tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_UNBALANCED_WHITE/**,tests/test_open_vp_cal/resources/export/patches/OpenVPCal_Wall1_ITU_R_BT_2020_ST_2084/**"

      # 4. Checkout fetched LFS files (by glob pattern)
      - name: Checkout LFS files in our two test-resource folders
        run: |
          git lfs checkout \
            tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_balanced/** \
            tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_UNBALANCED_WHITE/** \
            tests/test_open_vp_cal/resources/export/patches/OpenVPCal_Wall1_ITU_R_BT_2020_ST_2084/ **

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV CLI
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build Python environment
        run: uv build

      - name: Run tests
        run: uv run pytest ./tests -v --maxfail=1