name: Python CI/CD Workflow

on:
  push:
    branches:
      - feature/ci
  pull_request:
    branches:
      - feature/ci

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (no LFS)
        uses: actions/checkout@v3
        with:
          lfs: false

      # Install Git LFS and disable automatic smudge (download)
      - name: Install Git LFS & disable auto-smudge
        run: |
          brew install git-lfs
          git lfs install --skip-smudge

      # Fetch only the LFS files that we use across lots of tests as the whole set is too large
      - name: Fetch specific LFS folder
        run: |
          git lfs fetch --include="tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_balanced/**"

      # Replace pointers with real files for that folder
      - name: Checkout fetched LFS files
        run: |
          git lfs checkout --include="tests/test_open_vp_cal/resources/TEST_EXR_OPENVPCAL_balanced/**"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install UV CLI
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Build Python environment
        run: uv build

      - name: Run tests
        run: uv run pytest ./tests -v --maxfail=1