name: Python CI/CD Workflow

on:
  push:
    branches:
      - feature/ci
  pull_request:
    branches:
      - feature/ci

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      # Restore the .git directory from the cache
      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ hashFiles('.git/HEAD') }}
          restore-keys: |
            ${{ runner.os }}-git-

      # Check out the repository with LFS support
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          lfs: false  # Enable Git LFS support

        # Step 1: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: OpenVPCal
          miniconda-version: "latest"

      # Step 2: Create and activate the conda environment (if not using environment.yml)
      - name: Create and activate conda environment
        run: |
          conda create --name OpenVPCal python=3.11 -y
          conda activate OpenVPCal